import React from 'react'
// import { devDelay } from '../utils/devDelay'
export const metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
};
const page = async () => {
    // await devDelay()
    metadata.title="About Page"
      metadata.description="about Desc"

    return (
        <>
            <div>
                <h1 className='text-3xl py-10'>
                    About Us
                </h1>
            </div>
        </>
    )
}

export default page
