import BannerSection from "./components/home-component/BannerSection";
import LatestProduct from "./components/home-component/LatestProduct";



export const metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
};
export default async function Home() {

  metadata.title="Home Page"
  metadata.description="Home Desc"


  return (
    <>
      <BannerSection />
      <LatestProduct/>
      <div className="text-2xl text-center mt-5">
        Main Page
      </div>
    </>
  );
}
